#pragma once
#include <stdint.h>
// UIPathData
struct UIPathData_t1177;
// System.Object
#include "mscorlib_System_Object.h"
// UIInfo
struct UIInfo_t1961  : public Object_t
{
};
struct UIInfo_t1961_StaticFields{
	// UIPathData UIInfo::SysShopPageItem
	UIPathData_t1177 * ___SysShopPageItem;
	// UIPathData UIInfo::SysShopPage
	UIPathData_t1177 * ___SysShopPage;
	// UIPathData UIInfo::MailListItem
	UIPathData_t1177 * ___MailListItem;
	// UIPathData UIInfo::RelationNameListItem
	UIPathData_t1177 * ___RelationNameListItem;
	// UIPathData UIInfo::AwardListItem
	UIPathData_t1177 * ___AwardListItem;
	// UIPathData UIInfo::ChannelListItem
	UIPathData_t1177 * ___ChannelListItem;
	// UIPathData UIInfo::PVPSkillListItem
	UIPathData_t1177 * ___PVPSkillListItem;
	// UIPathData UIInfo::PVPRecordListItem
	UIPathData_t1177 * ___PVPRecordListItem;
	// UIPathData UIInfo::AutoDrugItem
	UIPathData_t1177 * ___AutoDrugItem;
	// UIPathData UIInfo::HuaShanMemberListItem
	UIPathData_t1177 * ___HuaShanMemberListItem;
	// UIPathData UIInfo::AchieveItem
	UIPathData_t1177 * ___AchieveItem;
	// UIPathData UIInfo::BackPackItem
	UIPathData_t1177 * ___BackPackItem;
	// UIPathData UIInfo::EquipStrengthenItem
	UIPathData_t1177 * ___EquipStrengthenItem;
	// UIPathData UIInfo::PlayerListItem
	UIPathData_t1177 * ___PlayerListItem;
	// UIPathData UIInfo::PlayerFindItem
	UIPathData_t1177 * ___PlayerFindItem;
	// UIPathData UIInfo::SceneMapTransmitPoint
	UIPathData_t1177 * ___SceneMapTransmitPoint;
	// UIPathData UIInfo::PopMenuItem
	UIPathData_t1177 * ___PopMenuItem;
	// UIPathData UIInfo::MissionItem
	UIPathData_t1177 * ___MissionItem;
	// UIPathData UIInfo::MissionLogItem
	UIPathData_t1177 * ___MissionLogItem;
	// UIPathData UIInfo::PartnerSkillItem
	UIPathData_t1177 * ___PartnerSkillItem;
	// UIPathData UIInfo::PartnerFrameItem
	UIPathData_t1177 * ___PartnerFrameItem;
	// UIPathData UIInfo::MountItem
	UIPathData_t1177 * ___MountItem;
	// UIPathData UIInfo::TitleInvestitiveItem
	UIPathData_t1177 * ___TitleInvestitiveItem;
	// UIPathData UIInfo::FastReplyItem
	UIPathData_t1177 * ___FastReplyItem;
	// UIPathData UIInfo::LastSpeakerItem
	UIPathData_t1177 * ___LastSpeakerItem;
	// UIPathData UIInfo::FashionItem
	UIPathData_t1177 * ___FashionItem;
	// UIPathData UIInfo::ConsignSaleBagItem
	UIPathData_t1177 * ___ConsignSaleBagItem;
	// UIPathData UIInfo::ConsignSaleBuyItem
	UIPathData_t1177 * ___ConsignSaleBuyItem;
	// UIPathData UIInfo::ConsignSaleMySaleItem
	UIPathData_t1177 * ___ConsignSaleMySaleItem;
	// UIPathData UIInfo::ConsignSaleQualityItem
	UIPathData_t1177 * ___ConsignSaleQualityItem;
	// UIPathData UIInfo::ConsignSaleClassItem
	UIPathData_t1177 * ___ConsignSaleClassItem;
	// UIPathData UIInfo::ConsignSaleSubClassItem
	UIPathData_t1177 * ___ConsignSaleSubClassItem;
	// UIPathData UIInfo::TeamPlatformItem
	UIPathData_t1177 * ___TeamPlatformItem;
	// UIPathData UIInfo::SkillRootButtonItem
	UIPathData_t1177 * ___SkillRootButtonItem;
	// UIPathData UIInfo::SkillRootBarItem
	UIPathData_t1177 * ___SkillRootBarItem;
	// UIPathData UIInfo::YuanBaoShopItem
	UIPathData_t1177 * ___YuanBaoShopItem;
	// UIPathData UIInfo::DropItemHeadInfo
	UIPathData_t1177 * ___DropItemHeadInfo;
	// UIPathData UIInfo::PlayerHeadInfo
	UIPathData_t1177 * ___PlayerHeadInfo;
	// UIPathData UIInfo::FellowHeadInfo
	UIPathData_t1177 * ___FellowHeadInfo;
	// UIPathData UIInfo::NPCHeadInfo
	UIPathData_t1177 * ___NPCHeadInfo;
	// UIPathData UIInfo::MercenaryListItem
	UIPathData_t1177 * ___MercenaryListItem;
	// UIPathData UIInfo::LivingSkillFormulaItem
	UIPathData_t1177 * ___LivingSkillFormulaItem;
	// UIPathData UIInfo::LivingSkillStuffItem
	UIPathData_t1177 * ___LivingSkillStuffItem;
	// UIPathData UIInfo::MasterMemberItem
	UIPathData_t1177 * ___MasterMemberItem;
	// UIPathData UIInfo::MasterReserveMemberItem
	UIPathData_t1177 * ___MasterReserveMemberItem;
	// UIPathData UIInfo::MasterPreviewItem
	UIPathData_t1177 * ___MasterPreviewItem;
	// UIPathData UIInfo::WorldBossListItem
	UIPathData_t1177 * ___WorldBossListItem;
	// UIPathData UIInfo::DamageBoard
	UIPathData_t1177 * ___DamageBoard;
	// UIPathData UIInfo::BackCamera
	UIPathData_t1177 * ___BackCamera;
	// UIPathData UIInfo::PvPRankListItem
	UIPathData_t1177 * ___PvPRankListItem;
	// UIPathData UIInfo::PowerPushListItem
	UIPathData_t1177 * ___PowerPushListItem;
	// UIPathData UIInfo::PowerPushReliveListItem
	UIPathData_t1177 * ___PowerPushReliveListItem;
	// UIPathData UIInfo::SwordsManItem
	UIPathData_t1177 * ___SwordsManItem;
	// UIPathData UIInfo::SwordsManShopItem
	UIPathData_t1177 * ___SwordsManShopItem;
	// UIPathData UIInfo::CangKuItem
	UIPathData_t1177 * ___CangKuItem;
	// UIPathData UIInfo::CangKuBackItem
	UIPathData_t1177 * ___CangKuBackItem;
	// UIPathData UIInfo::MasterShopItem
	UIPathData_t1177 * ___MasterShopItem;
	// UIPathData UIInfo::AutoSelSkillItem
	UIPathData_t1177 * ___AutoSelSkillItem;
	// UIPathData UIInfo::MakeWaistbandItem
	UIPathData_t1177 * ___MakeWaistbandItem;
	// UIPathData UIInfo::WuLinMemberListItem
	UIPathData_t1177 * ___WuLinMemberListItem;
	// UIPathData UIInfo::RollNotice
	UIPathData_t1177 * ___RollNotice;
	// UIPathData UIInfo::TargetFrameRoot
	UIPathData_t1177 * ___TargetFrameRoot;
	// UIPathData UIInfo::PlayerFrameRoot
	UIPathData_t1177 * ___PlayerFrameRoot;
	// UIPathData UIInfo::MenuBarRoot
	UIPathData_t1177 * ___MenuBarRoot;
	// UIPathData UIInfo::FunctionButtonRoot
	UIPathData_t1177 * ___FunctionButtonRoot;
	// UIPathData UIInfo::MissionDialogAndLeftTabsRoot
	UIPathData_t1177 * ___MissionDialogAndLeftTabsRoot;
	// UIPathData UIInfo::ChatFrameRoot
	UIPathData_t1177 * ___ChatFrameRoot;
	// UIPathData UIInfo::ExpRoot
	UIPathData_t1177 * ___ExpRoot;
	// UIPathData UIInfo::JoyStickRoot
	UIPathData_t1177 * ___JoyStickRoot;
	// UIPathData UIInfo::SkillBarRoot
	UIPathData_t1177 * ___SkillBarRoot;
	// UIPathData UIInfo::PlayerHitsRoot
	UIPathData_t1177 * ___PlayerHitsRoot;
	// UIPathData UIInfo::SkillProgress
	UIPathData_t1177 * ___SkillProgress;
	// UIPathData UIInfo::CollectItemSlider
	UIPathData_t1177 * ___CollectItemSlider;
	// UIPathData UIInfo::RechargeBar
	UIPathData_t1177 * ___RechargeBar;
	// UIPathData UIInfo::PkNotice
	UIPathData_t1177 * ___PkNotice;
	// UIPathData UIInfo::MessageBox
	UIPathData_t1177 * ___MessageBox;
	// UIPathData UIInfo::AddFriend
	UIPathData_t1177 * ___AddFriend;
	// UIPathData UIInfo::OpenServer
	UIPathData_t1177 * ___OpenServer;
	// UIPathData UIInfo::SysShop
	UIPathData_t1177 * ___SysShop;
	// UIPathData UIInfo::SceneMapRoot
	UIPathData_t1177 * ___SceneMapRoot;
	// UIPathData UIInfo::WorldMapWindow
	UIPathData_t1177 * ___WorldMapWindow;
	// UIPathData UIInfo::MissionInfoController
	UIPathData_t1177 * ___MissionInfoController;
	// UIPathData UIInfo::MarryRoot
	UIPathData_t1177 * ___MarryRoot;
	// UIPathData UIInfo::OptionDialogRoot
	UIPathData_t1177 * ___OptionDialogRoot;
	// UIPathData UIInfo::ChatInfoRoot
	UIPathData_t1177 * ___ChatInfoRoot;
	// UIPathData UIInfo::ServerChoose
	UIPathData_t1177 * ___ServerChoose;
	// UIPathData UIInfo::RoleChoose
	UIPathData_t1177 * ___RoleChoose;
	// UIPathData UIInfo::RoleCreate
	UIPathData_t1177 * ___RoleCreate;
	// UIPathData UIInfo::ChannelChange
	UIPathData_t1177 * ___ChannelChange;
	// UIPathData UIInfo::Activity
	UIPathData_t1177 * ___Activity;
	// UIPathData UIInfo::PvPShopRoot
	UIPathData_t1177 * ___PvPShopRoot;
	// UIPathData UIInfo::PKSetInfo
	UIPathData_t1177 * ___PKSetInfo;
	// UIPathData UIInfo::AwardRoot
	UIPathData_t1177 * ___AwardRoot;
	// UIPathData UIInfo::MoneyTreeRoot
	UIPathData_t1177 * ___MoneyTreeRoot;
	// UIPathData UIInfo::DailyDrawRoot
	UIPathData_t1177 * ___DailyDrawRoot;
	// UIPathData UIInfo::HelpController
	UIPathData_t1177 * ___HelpController;
	// UIPathData UIInfo::YuanBaoShop
	UIPathData_t1177 * ___YuanBaoShop;
	// UIPathData UIInfo::RankRoot
	UIPathData_t1177 * ___RankRoot;
	// UIPathData UIInfo::ZiPaiRoot
	UIPathData_t1177 * ___ZiPaiRoot;
	// UIPathData UIInfo::CheckPowerRoot
	UIPathData_t1177 * ___CheckPowerRoot;
	// UIPathData UIInfo::VictoryScoreRoot
	UIPathData_t1177 * ___VictoryScoreRoot;
	// UIPathData UIInfo::SNSRoot
	UIPathData_t1177 * ___SNSRoot;
	// UIPathData UIInfo::SNSShareCodeRoot
	UIPathData_t1177 * ___SNSShareCodeRoot;
	// UIPathData UIInfo::SNSShareRoot
	UIPathData_t1177 * ___SNSShareRoot;
	// UIPathData UIInfo::Recharge
	UIPathData_t1177 * ___Recharge;
	// UIPathData UIInfo::ChangeName
	UIPathData_t1177 * ___ChangeName;
	// UIPathData UIInfo::ChargeActivity
	UIPathData_t1177 * ___ChargeActivity;
	// UIPathData UIInfo::CangKu
	UIPathData_t1177 * ___CangKu;
	// UIPathData UIInfo::BlackMarket
	UIPathData_t1177 * ___BlackMarket;
	// UIPathData UIInfo::VipRoot
	UIPathData_t1177 * ___VipRoot;
	// UIPathData UIInfo::ShareRoot
	UIPathData_t1177 * ___ShareRoot;
	// UIPathData UIInfo::ChristmasController
	UIPathData_t1177 * ___ChristmasController;
	// UIPathData UIInfo::PresentRoot
	UIPathData_t1177 * ___PresentRoot;
	// UIPathData UIInfo::FestivalController
	UIPathData_t1177 * ___FestivalController;
	// UIPathData UIInfo::FlowerEggRoot
	UIPathData_t1177 * ___FlowerEggRoot;
	// UIPathData UIInfo::GongJiShopRoot
	UIPathData_t1177 * ___GongJiShopRoot;
	// UIPathData UIInfo::PicGuideRoot
	UIPathData_t1177 * ___PicGuideRoot;
	// UIPathData UIInfo::NewServerActivityRoot
	UIPathData_t1177 * ___NewServerActivityRoot;
	// UIPathData UIInfo::MissionGame
	UIPathData_t1177 * ___MissionGame;
	// UIPathData UIInfo::StoryCopySceneResultRoot
	UIPathData_t1177 * ___StoryCopySceneResultRoot;
	// UIPathData UIInfo::StoryCopySceneInfoRoot
	UIPathData_t1177 * ___StoryCopySceneInfoRoot;
	// UIPathData UIInfo::StoryDialogRoot
	UIPathData_t1177 * ___StoryDialogRoot;
	// UIPathData UIInfo::MovieUI
	UIPathData_t1177 * ___MovieUI;
	// UIPathData UIInfo::ShiCiRoot
	UIPathData_t1177 * ___ShiCiRoot;
	// UIPathData UIInfo::JianPuRoot
	UIPathData_t1177 * ___JianPuRoot;
	// UIPathData UIInfo::ItemTooltipsRoot
	UIPathData_t1177 * ___ItemTooltipsRoot;
	// UIPathData UIInfo::EquipTooltipsRoot
	UIPathData_t1177 * ___EquipTooltipsRoot;
	// UIPathData UIInfo::NumChoose
	UIPathData_t1177 * ___NumChoose;
	// UIPathData UIInfo::FlowerNumChoose
	UIPathData_t1177 * ___FlowerNumChoose;
	// UIPathData UIInfo::QueueWindow
	UIPathData_t1177 * ___QueueWindow;
	// UIPathData UIInfo::RelationNamePopWindow
	UIPathData_t1177 * ___RelationNamePopWindow;
	// UIPathData UIInfo::AutoDrug
	UIPathData_t1177 * ___AutoDrug;
	// UIPathData UIInfo::SwordsManTooltipsRoot
	UIPathData_t1177 * ___SwordsManTooltipsRoot;
	// UIPathData UIInfo::MoneyTipRoot
	UIPathData_t1177 * ___MoneyTipRoot;
	// UIPathData UIInfo::MissionTooltipsRoot
	UIPathData_t1177 * ___MissionTooltipsRoot;
	// UIPathData UIInfo::FellowTooltipsRoot
	UIPathData_t1177 * ___FellowTooltipsRoot;
	// UIPathData UIInfo::Belle
	UIPathData_t1177 * ___Belle;
	// UIPathData UIInfo::FlyWingRoot
	UIPathData_t1177 * ___FlyWingRoot;
	// UIPathData UIInfo::EquipStren
	UIPathData_t1177 * ___EquipStren;
	// UIPathData UIInfo::BackPackRoot
	UIPathData_t1177 * ___BackPackRoot;
	// UIPathData UIInfo::RelationRoot
	UIPathData_t1177 * ___RelationRoot;
	// UIPathData UIInfo::MissionLogRoot
	UIPathData_t1177 * ___MissionLogRoot;
	// UIPathData UIInfo::PartnerFrameRoot
	UIPathData_t1177 * ___PartnerFrameRoot;
	// UIPathData UIInfo::RoleView
	UIPathData_t1177 * ___RoleView;
	// UIPathData UIInfo::SkillInfo
	UIPathData_t1177 * ___SkillInfo;
	// UIPathData UIInfo::SystemAndAutoFight
	UIPathData_t1177 * ___SystemAndAutoFight;
	// UIPathData UIInfo::ConsignSaleRoot
	UIPathData_t1177 * ___ConsignSaleRoot;
	// UIPathData UIInfo::GuildRoot
	UIPathData_t1177 * ___GuildRoot;
	// UIPathData UIInfo::Restaurant
	UIPathData_t1177 * ___Restaurant;
	// UIPathData UIInfo::LivingSkill
	UIPathData_t1177 * ___LivingSkill;
	// UIPathData UIInfo::OtherRoleView
	UIPathData_t1177 * ___OtherRoleView;
	// UIPathData UIInfo::SwordsManLevelUpRoot
	UIPathData_t1177 * ___SwordsManLevelUpRoot;
	// UIPathData UIInfo::SwordsManShopRoot
	UIPathData_t1177 * ___SwordsManShopRoot;
	// UIPathData UIInfo::SwordsManRoot
	UIPathData_t1177 * ___SwordsManRoot;
	// UIPathData UIInfo::Biography
	UIPathData_t1177 * ___Biography;
	// UIPathData UIInfo::Notice
	UIPathData_t1177 * ___Notice;
	// UIPathData UIInfo::JoyStickTipInfo
	UIPathData_t1177 * ___JoyStickTipInfo;
	// UIPathData UIInfo::MountFrameRoot
	UIPathData_t1177 * ___MountFrameRoot;
	// UIPathData UIInfo::FashionRoot
	UIPathData_t1177 * ___FashionRoot;
	// UIPathData UIInfo::CentreNotice
	UIPathData_t1177 * ___CentreNotice;
	// UIPathData UIInfo::PopMenuRoot
	UIPathData_t1177 * ___PopMenuRoot;
	// UIPathData UIInfo::PowerRemindRoot
	UIPathData_t1177 * ___PowerRemindRoot;
	// UIPathData UIInfo::EquipRemindRoot
	UIPathData_t1177 * ___EquipRemindRoot;
	// UIPathData UIInfo::UseItemRemindRoot
	UIPathData_t1177 * ___UseItemRemindRoot;
	// UIPathData UIInfo::ItemRemindRoot
	UIPathData_t1177 * ___ItemRemindRoot;
	// UIPathData UIInfo::CountDown
	UIPathData_t1177 * ___CountDown;
	// UIPathData UIInfo::ChallengeRewardRoot
	UIPathData_t1177 * ___ChallengeRewardRoot;
	// UIPathData UIInfo::LevelupTip
	UIPathData_t1177 * ___LevelupTip;
	// UIPathData UIInfo::NewPlayerGuidRoot
	UIPathData_t1177 * ___NewPlayerGuidRoot;
	// UIPathData UIInfo::GuaJiGuild
	UIPathData_t1177 * ___GuaJiGuild;
	// UIPathData UIInfo::NewItemGetRoot
	UIPathData_t1177 * ___NewItemGetRoot;
	// UIPathData UIInfo::BonusItemGetRoot
	UIPathData_t1177 * ___BonusItemGetRoot;
	// UIPathData UIInfo::ShareTargetChooseRoot
	UIPathData_t1177 * ___ShareTargetChooseRoot;
	// UIPathData UIInfo::UpdateLoadingBar
	UIPathData_t1177 * ___UpdateLoadingBar;
	// UIPathData UIInfo::MercenaryWindowRoot
	UIPathData_t1177 * ___MercenaryWindowRoot;
	// UIPathData UIInfo::WorldBossWindowRoot
	UIPathData_t1177 * ___WorldBossWindowRoot;
	// UIPathData UIInfo::GuilWarRetWindow
	UIPathData_t1177 * ___GuilWarRetWindow;
	// UIPathData UIInfo::GuilWarPushMessage
	UIPathData_t1177 * ___GuilWarPushMessage;
	// UIPathData UIInfo::RequestReviewWindow
	UIPathData_t1177 * ___RequestReviewWindow;
	// UIPathData UIInfo::Relive
	UIPathData_t1177 * ___Relive;
};
